taxi/lib/taxi_web/router.ex
defmodule TaxiWeb.Router do
  use TaxiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TaxiWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Taxi.Authentication, repo: Taxi.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaxiWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/bookings", BookingController
    resources "/taxi", TaxiController
    get "/taxi/:id/complete-ride", TaxiController, :completeRide

  end

  # Other scopes may use custom stacks.
  # scope "/api", TaxiWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TaxiWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

taxi/lib/taxi_web/views/layout_view.ex
defmodule TaxiWeb.LayoutView do
  use TaxiWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

taxi/lib/taxi_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

taxi/lib/taxi_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

taxi/lib/taxi_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Taxi", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
        <nav class="pull-right">
          <ul>
          <%= if @conn.assigns.current_user do %>
            <li><h4>You are logged in as <%= @conn.assigns.current_user.email %></h4></li>
            <li><%= button "Log out", to: Routes.session_path(@conn, :delete, @conn.assigns.current_user), method: "delete" %></li>
          <% else %>
            <li><h4>Welcome, guest :)</h4></li>
            <li><%= link "Log in", to: Routes.session_path(@conn, :new), class: "button button-outline" %> or <%= link "Sign up", to: Routes.user_path(@conn, :new), class: "button" %></li>
          <% end %>
          </ul>
        </nav>
    </header>
    <%= @inner_content %>
  </body>
</html>