taxi/lib/taxi_web/router.ex
defmodule TaxiWeb.Router do
  use TaxiWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TaxiWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Taxi.Authentication, repo: Taxi.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaxiWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/bookings", BookingController
    resources "/taxi", TaxiController
    get "/taxi/:id/complete-ride", TaxiController, :completeRide

  end

  # Other scopes may use custom stacks.
  # scope "/api", TaxiWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: TaxiWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

taxi/lib/taxi/accounts/user.ex
defmodule Taxi.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :fullname,  :string
    field :email,     :string
    field :age,       :integer
    field :password,  :string

    timestamps()
  end

  def changeset(user, params \\ %{}) do
    user
    |> cast(params, [:fullname, :email, :age, :password])
    |> validate_required([:fullname, :email, :age, :password])
    |> validate_format(:email, ~r/@/)
    |> validate_inclusion(:age, 18..100)
    |> unique_constraint(:email)
  end

end

taxi/lib/taxi/application.ex
defmodule Taxi.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Taxi.Repo,
      # Start the Telemetry supervisor
      TaxiWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Taxi.PubSub},
      # Start the Endpoint (http/https)
      TaxiWeb.Endpoint
      # Start a worker by calling: Taxi.Worker.start_link(arg)
      # {Taxi.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Taxi.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    TaxiWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

taxi/lib/taxi/mailer.ex
defmodule Taxi.Mailer do
  use Swoosh.Mailer, otp_app: :taxi
end

taxi/lib/taxi/repo.ex
defmodule Taxi.Repo do
  use Ecto.Repo,
    otp_app: :taxi,
    adapter: Ecto.Adapters.Postgres
end

taxi/lib/taxi/sales/allocation.ex
defmodule Taxi.Sales.Allocation do
  use Ecto.Schema
  import Ecto.Changeset

  schema "allocations" do
    field :status, :string
    belongs_to :booking, Takso.Sales.Booking
    belongs_to :taxi, Takso.Sales.Taxi

    timestamps()
  end

  @doc false
  def changeset(allocation, attrs) do
    allocation
    |> cast(attrs, [:status])
    |> validate_required([:status])
  end
end

taxi/lib/taxi/sales/booking.ex
defmodule Taxi.Sales.Booking do
  use Ecto.Schema
  import Ecto.Changeset

  schema "bookings" do
    field :dropoff_address, :string
    field :pickup_address, :string
    field :distance, :decimal
    field :status, :string, default: "OPEN"
    belongs_to :user, Taxi.Accounts.User

    timestamps()
  end

  @doc false
  def changeset(booking, attrs) do
    booking
    |> cast(attrs, [:pickup_address, :dropoff_address, :distance, :status])
    |> validate_required([:pickup_address, :dropoff_address, :distance])
    |> validate_number(:distance, greater_than_or_equal_to: 0)
    |> validate_dropoff()
  end


  defp validate_dropoff(changeset) do
    pickup = get_field(changeset, :pickup_address)
    dropoff = get_field(changeset, :dropoff_address)
    if pickup == dropoff do
      add_error(changeset, :dropoff_address, "Pickup and Dropoff addresses cannot be the same")
    else
      changeset
    end
  end

end

taxi/lib/taxi/sales/taxi.ex
defmodule Taxi.Sales.Taxi do
  use Ecto.Schema
  import Ecto.Changeset

  schema "taxis" do
    field :location, :string
    field :status, :string
    field :total_seat, :integer
    field :cost_per_kilo, :decimal
    belongs_to :user, Taxi.Accounts.User
    field :active, :boolean, default: true

    timestamps()
  end

  @doc false
  def changeset(taxi, attrs) do
    taxi
    |> cast(attrs, [:location, :status, :total_seat, :cost_per_kilo])
    |> validate_required([:location, :status])
  end
end

taxi/lib/taxi_web/controllers/taxi_controller.ex
defmodule TaxiWeb.TaxiController do
  use TaxiWeb, :controller
  alias Taxi.Repo
  alias Taxi.Accounts.User
  alias Taxi.Sales.{Taxi, Allocation, Booking}

  alias Ecto.{Changeset, Multi}
  import Ecto.Query, only: [from: 2]

  def index(conn, _params) do
    user = getCurrentUser(conn)
    query = from t in Taxi, where: t.user_id == ^user.id and t.active, select: t
    # for simplicity, let's assume one account has one Taxi
    taxi = Repo.one(query)
    if taxi != nil do
      bookings = getRideHistory(taxi.id)
      allot = getAllocation(taxi.id)
      if allot != nil do
        rideToComplete = getCurrentRide(allot.id)
        render(conn, "index.html", taxi: taxi, rideToComplete: rideToComplete, bookings: bookings)
      else
        render(conn, "index.html", taxi: taxi, rideToComplete: nil, bookings: bookings)
      end
    end

    render(conn, "index.html", taxi: taxi, rideToComplete: nil, bookings: nil)
  end

  def new(conn, _params) do
    changeset = Taxi.changeset(%Taxi{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"taxi" => taxi_params}) do
    user = getCurrentUser(conn)
    changeset = Taxi.changeset(%Taxi{}, taxi_params)
                |> Changeset.put_change(:user, user)
    case Repo.insert(changeset) do
      {:ok, taxi} ->
        conn
        |> put_flash(:info, "Register Taxi successfully")
        |> redirect(to: Routes.taxi_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => id}) do
    taxi = Repo.get!(Taxi, id)
    changeset = Taxi.changeset(taxi, %{})
    render(conn, "edit.html", taxi: taxi, changeset: changeset)
  end

  def update(conn, %{"id" => id, "taxi" => taxi_params}) do
    taxi = Repo.get!(Taxi, id)
    changeset = Taxi.changeset(taxi, taxi_params)

    Repo.update(changeset)
    conn
    |> put_flash(:info, "Taxi detail updated")
    |> redirect(to: Routes.taxi_path(conn, :index))
  end

  def delete(conn, %{"id" => id}) do
    taxi = Repo.get!(Taxi, id)
    # Repo.delete!(taxi)
    # History will gone, if we actually deleted the driver
      Multi.new
      |> Multi.update(:taxi, Taxi.changeset(taxi, %{}) |> Changeset.put_change(:active, false) |> Changeset.put_change(:status, "BUSY"))
      |> Repo.transaction

    conn
    |> put_flash(:info, "Your are not a Taxi driver anymore")
    |> redirect(to: Routes.page_path(conn, :index))
  end

  def completeRide(conn, %{"id" => id}) do
    user = getCurrentUser(conn)
    taxi = Repo.get(Taxi, id)

    if taxi != nil and taxi.user_id == user.id do
      allot = getAllocation(id)
      if allot != nil do
        Multi.new
        |> Multi.update(:allocation, Allocation.changeset(allot, %{}) |> Changeset.put_change(:status, "COMPLETED"))
        |> Multi.update(:taxi, Taxi.changeset(taxi, %{}) |> Changeset.put_change(:status, "AVAILABLE"))
        |> Repo.transaction
        conn
        |> put_flash(:info, "Completed ride")
        |> redirect(to: Routes.taxi_path(conn, :index))
      end
    end

    conn
      |> put_flash(:error, "You are not authourize to perform this action")
      |> redirect(to: Routes.page_path(conn, :index))
  end

  defp getCurrentUser(conn) do
    user = conn.assigns.current_user
    if user == nil do
      conn |> put_flash(:error, "Please login first")
           |> redirect(to: Routes.session_path(conn, :new))
    end
    user
  end

  defp getAllocation(id) do
    query = from a in Allocation,
      where: a.taxi_id == ^id and a.status == "ALLOCATED",
      order_by: [asc: :inserted_at],
      select: a
    Repo.all(query) |> List.first
  end

  defp getRideHistory(id) do
    query = from b in Booking,
      join: a in Allocation, on: a.booking_id == b.id and a.taxi_id == ^id,
      left_join: u in User, on: u.id == b.user_id,
      order_by: [asc: :inserted_at],
      select: b
    Repo.all(query) |> Repo.preload(:user)
  end

  defp getCurrentRide(id) do
    query = from b in Booking,
      join: a in Allocation, on: a.booking_id == b.id and a.id == ^id,
      left_join: u in User, on: u.id == b.user_id,
      order_by: [asc: :inserted_at],
      select: b
    Repo.one(query) |> Repo.preload(:user)
  end

end

taxi/lib/taxi_web/views/taxi_view.ex
defmodule TaxiWeb.TaxiView do
  use TaxiWeb, :view
end

taxi/lib/taxi_web/templates/taxi/edit.html.eex
<h2>Edit Taxi details</h2>

<%=render "form.html", changeset: @changeset,
                        action: Routes.taxi_path(@conn, :update, @taxi) %>

taxi/lib/taxi_web/templates/taxi/form.html.eex
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= form_for @changeset, @action, fn taxi -> %>
    <div class="form-group">
      <%= label taxi, :location, class: "control-label" %>
      <%= text_input taxi, :location, class: "form-control" %>
      <%= error_tag taxi, :location %>
    </div>

    <%# for testing purpose, this field is automatically updated %>
    <div class="form-group" hidden>
      <%= label taxi, :status, class: "control-label" %>
      <%= select taxi, :status, ["AVAILABLE": "AVAILABLE", "BUSY": "BUSY"], class: "form-control" %>
      <%= error_tag taxi, :status %>
    </div>
    
    <div class="form-group">
      <%= label taxi, :total_seat, class: "control-label" %>
      <%= number_input taxi, :total_seat, class: "form-control", min: "0" %>
      <%= error_tag taxi, :total_seat %>
    </div>
    <div class="form-group">
      <%= label taxi, :cost_per_kilo, class: "control-label" %>
      <%= number_input taxi, :cost_per_kilo, class: "form-control", min: "0", step: "0.1" %>
      <%= error_tag taxi, :cost_per_kilo %>
    </div>

    <div class="form-group">
      <%= submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>

taxi/lib/taxi_web/templates/taxi/index.html.eex
<h2>Manage Taxi</h2>
<%= if @taxi == nil do %>
    <%= link "Become a driver", to: Routes.taxi_path(@conn, :new), class: "button" %>  
<% else %>
    <%= if @rideToComplete do %>
        <table class="table">
            <caption>Current ride</caption>
            <thead>
                <tr>
                <th>Pick up</th>
                <th>Drop off</th>
                <th>Distance (km)</th>
                <th>Customer</th>
                <th>Date</th>
                <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                <td><%= @rideToComplete.pickup_address %></td>
                <td><%= @rideToComplete.dropoff_address %></td>
                <td><%= @rideToComplete.distance %></td>
                <td><%= @rideToComplete.user.fullname %></td>
                <td><%= @rideToComplete.inserted_at %></td>
                <td><%= link "Complete ride", to: Routes.taxi_path(@conn, :completeRide, @taxi), class: "button" %>  </td>
                </tr>
            </tbody>
        </table>
    <% end %>

    <table class="table">
        <caption>History</<caption>
        <thead>
            <tr>
            <th>Pick up</th>
            <th>Drop off</th>
            <th>Distance (km)</th>
            <th>Customer</th>
            <th>Date</th>
            <th></th>
            </tr>
        </thead>
        <tbody>
        <%= for booking <- @bookings do %>
            <tr>
            <td><%= booking.pickup_address %></td>
            <td><%= booking.dropoff_address %></td>
            <td><%= booking.distance %></td>
            <td><%= booking.user.fullname %></td>
            <td><%= booking.inserted_at %></td>
            <td class="text-right"><%= link "Show", to: Routes.booking_path(@conn, :show, booking), class: "button button-outline" %></td>
            </tr>
        <% end %>
        </tbody>
    </table>

    <br/><%= link "Edit Taxi detail", to: Routes.taxi_path(@conn, :edit, @taxi), class: "button" %>  
    <br/><%= button "Unregister as a driver", to: Routes.taxi_path(@conn, :delete, @taxi), method: :delete, data: [confirm: "Are you sure?"], class: "alert-danger" %>  
<% end %>

taxi/lib/taxi_web/templates/taxi/new.html.eex
<h2>Register as Taxi driver</h2>

<%= render "form.html", changeset: @changeset,
                        action: Routes.taxi_path(@conn, :create) %>